{
 "title": "Spacefarmers.io",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "query0" },
   {
    "name": "LauncherID",
    "query": {}
   },
   {
    "name": "FarmerName",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Bluebox Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocks compactified [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({chia_service_type=\"full_node\",job=\"timelord\"}|~\"Replaced compact proof\"[24h])"
    }
   ]
  },
  {
   "title": "Duplicates [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({chia_service_type=\"full_node\",job=\"timelord\"}|~\"Already compactified block\"[24h])"
    }
   ]
  },
  {
   "title": "Avg Iterations by vdf [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"timelord\"} |~ \"tag=\" | logfmt | tag = \"bluebox_finish\" | unwrap iterations [24h]) by (field_vdf)",
     "legendFormat": "{{field_vdf}}"
    }
   ]
  },
  {
   "title": "Compact Blocks Received [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({chia_service_type=\"full_node\",job=\"timelord\"}|~\"Received compact proof\"[24h])"
    }
   ]
  },
  {
   "title": "Avg Compaction Time by vdf [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"timelord\"} |~ \"tag=\" | logfmt | tag = \"bluebox_finish\" | unwrap duration [24h]) by (field_vdf)",
     "legendFormat": "{{field_vdf}}"
    }
   ]
  },
  {
   "title": "Heights by Blueboxes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg_over_time({job=\"timelord\"} |~ \"Received compact proof\" | logfmt | unwrap height [$__interval]) by (bluebox_index)",
     "legendFormat": "{{bluebox_index}}"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"timelord\"} |~ \"tag=\" | logfmt | tag = \"bluebox_finish\" | unwrap iterations [1m]) by (field_vdf)",
     "legendFormat": "field_vdf:{{field_vdf}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "avg iterations per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg_over_time({job=\"timelord\"} |~ \"tag=\" | logfmt | tag = \"bluebox_finish\" | unwrap iterations[1m]) by (field_vdf)\n/\navg_over_time({job=\"timelord\"} |~ \"tag=\" | logfmt | tag = \"bluebox_finish\" | unwrap duration[1m]) by (field_vdf)",
     "legendFormat": "field_vdf:{{field_vdf}}"
    }
   ]
  },
  {
   "title": "avg vdf compact time(s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "avg_over_time({job=\"timelord\"} |~ \"tag=\" | logfmt | tag = \"bluebox_finish\" | unwrap duration [1m]) by (field_vdf)",
     "legendFormat": "avg_compact_time_vdf_{{field_vdf}}"
    }
   ]
  },
  {
   "title": "Blocks compactified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "count_over_time({chia_service_type=\"full_node\",job=\"timelord\"}|~\"Replaced compact proof\"[15m])",
     "legendFormat": "Compactified"
    },
    {
     "expr": "count_over_time({chia_service_type=\"full_node\",job=\"timelord\"}|~\"Already compactified block\"[1m])",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "count_over_time({chia_service_type=\"full_node\",job=\"timelord\"}|~\"Received compact proof\"[15m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Pending Queue (count)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "min_over_time({job=\"timelord\"} |~ \"tag=\" | logfmt | tag = \"bluebox_launch\" | unwrap pending [1m]) by (unit)",
     "legendFormat": "queue_size"
    }
   ]
  },
  {
   "title": "wip/free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "min_over_time(\n  {job=\"timelord\"}\n  |~ \"tag=compact_launch\"\n  | pattern `<tsLocal> <service> <module>: <level> tag=<tag> <_> pending=<pending> wip=<wip> free_clients=<free>`\n  | unwrap wip [1m]\n) by (unit)",
     "legendFormat": "wip"
    },
    {
     "expr": "min_over_time(\n  {job=\"timelord\"}\n  |~ \"tag=compact_launch\"\n  | pattern `<tsLocal> <service> <module>: <level> tag=<tag> <_> pending=<pending> wip=<wip> free_clients=<free>`\n  | unwrap free [1m]\n) by (unit)",
     "legendFormat": "free_clients"
    },
    {
     "expr": "min_over_time(\n  {job=\"timelord\"}\n  |~ \"tag=bluebox_launch\"\n  | pattern `<tsLocal> <service> <module>: <level> tag=<tag> <_> pending=<pending> wip=<wip> free_clients=<free>`\n  | unwrap wip [1m]\n) by (unit)",
     "legendFormat": "wip"
    },
    {
     "expr": "min_over_time(\n  {job=\"timelord\"}\n  |~ \"tag=bluebox_launch\"\n  | pattern `<tsLocal> <service> <module>: <level> tag=<tag> <_> pending=<pending> wip=<wip> free_clients=<free>`\n  | unwrap free [1m]\n) by (unit)",
     "legendFormat": "free_clients"
    }
   ]
  },
  {
   "title": "Chia Blockchain Healthcheck",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Validation Time(s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "avg_over_time({chia_service_type=\"full_node\",job=\"fullnode\"}|~\"Added unfinished_block\"|pattern \"<_> validation time: <block_validation_time> seconds, <_>\"|unwrap block_validation_time[15s])",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "avg_over_time({chia_service_type=\"full_node\",job=\"timelord\"}|~\"Added unfinished_block\"|pattern \"<_> validation time: <block_validation_time> seconds, <_>\"|unwrap block_validation_time[15s])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Signage Points",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "count_over_time({chia_service_type=\"full_node\",job=\"fullnode\"}|~\"Finished sub slot\"[10m])",
       "legendFormat": "SS_{{job}}"
      },
      {
       "expr": "count_over_time({chia_service_type=\"full_node\",job=\"fullnode\"}|~\"Finished signage point\"[10m])",
       "legendFormat": "SP_{{job}}"
      },
      {
       "expr": "count_over_time({chia_service_type=\"full_node\",job=\"timelord\"}|~\"Finished sub slot\"[10m])",
       "legendFormat": "SS_{{job}}"
      },
      {
       "expr": "count_over_time({chia_service_type=\"full_node\",job=\"timelord\"}|~\"Finished signage point\"[10m])",
       "legendFormat": "SP_{{job}}"
      }
     ]
    },
    {
     "title": "Signage Points - fullnode",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "count_over_time({chia_service_type=\"full_node\",job=\"fullnode\"}|~\"Finished signage point|Finished sub slot\"[10m])",
       "legendFormat": "SP_{{job}}"
      }
     ]
    },
    {
     "title": "New Signage Point - rate limited",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "count_over_time({job=\"harvester\"}|~\"Peer surpassed rate limit\"|~\"new_signage_point_harvester\"[1m])"
      }
     ]
    },
    {
     "title": "Request Plots - rate limited",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 71 },
     "targets": [
      {
       "expr": "count_over_time({job=\"harvester\"}|~\"Peer surpassed rate limit\"|~\"request_plots\"[1m])"
      }
     ]
    },
    {
     "title": "No Signage Points found",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "count_over_time({chia_service_type=\"full_node\",job=\"fullnode\"}|~\"Don't have signage point\"[1m])"
      }
     ]
    },
    {
     "title": "Mempool Size (spends)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 79 },
     "targets": [
      {
       "expr": "avg_over_time({chia_service_type=\"full_node\",job=\"fullnode\"}|~\"Size of mempool\"|pattern \"<_> Size of mempool: <mempool_size> spends, <_>\"|unwrap mempool_size [30s])"
      }
     ]
    },
    {
     "title": "Signage Points Cached",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "count_over_time({chia_service_type=\"full_node\",job=\"fullnode\"}|~\"Don't have rc hash\"[1m])"
      }
     ]
    },
    {
     "title": "Mempool Cost",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max_over_time({chia_service_type=\"full_node\",job=\"fullnode\"}|~\"Size of mempool\"|pattern \"<_> cost: <mempool_cost> <_>\"|unwrap mempool_cost[30s])"
      }
     ]
    },
    {
     "title": "Cache miss for Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "count_over_time({chia_service_type=\"full_node\",job=\"fullnode\"}|~\"cache miss for block\"[1m])"
      }
     ]
    },
    {
     "title": "Blocks Full percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg_over_time({chia_service_type=\"full_node\",job=\"fullnode\"}|~\"Added unfinished_block\"|pattern \"<_> percent full: <block_percentage>%\"|unwrap block_percentage [30s])",
       "resolution": 1
      }
     ]
    }
   ]
  },
  {
   "title": "Chia Blockchain Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_blockchain_state_height{}"
      }
     ]
    },
    {
     "title": "OG vs NFT Plots",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 3, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "chia_nft_plots_size_bytes{instance=\"192.168.1.202:9100\"}",
       "legendFormat": "NFT Plots Overall Size"
      }
     ]
    },
    {
     "title": "Blockchain Fee",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 53 },
     "targets": [
      {
       "expr": "chia_rpc_blockchain_state_fee_amount{}/1000000000000",
       "legendFormat": "fee amount"
      }
     ]
    },
    {
     "title": "Fee Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_blockchain_state_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "chia_rpc_blockchain_state_difficulty{}",
       "legendFormat": "difficulty"
      }
     ]
    },
    {
     "title": "Netspace",
     "type": "stat",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_blockchain_state_netspace{}",
       "legendFormat": "netspace"
      }
     ]
    }
   ]
  },
  {
   "title": "Spacefarmers.io",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "My 24h Points - Pool Report",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "api_farmers_self_points24h{}", "legendFormat": " current Points" },
      {
       "expr": "chia_nft_plots_size_bytes{instance=\"192.168.1.202:9100\"}/1024/1024/1024/1024*100.98619",
       "legendFormat": "expected Points"
      },
      {
       "expr": "chia_nft_plots_size_bytes{instance=\"192.168.1.202:9100\"}/1024/1024/1024/1024*100.98619*1.1",
       "legendFormat": "+10%"
      },
      {
       "expr": "chia_nft_plots_size_bytes{instance=\"192.168.1.202:9100\"}/1024/1024/1024/1024*100.98619*0.9",
       "legendFormat": "-10%"
      },
      {
       "expr": "avg_over_time(api_farmers_self_points24h{}[24h])",
       "legendFormat": "avg over 24h"
      },
      {
       "expr": "avg_over_time(api_farmers_self_points24h{}[30d])",
       "legendFormat": "avg diff last 30d"
      }
     ]
    },
    {
     "title": "Partials per Hour - Pool Report",
     "type": "histogram",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "count_over_time({job=~\"fullnode\",log_mode=\"INFO\",system=\"chia\"} |=\"Submitting partial\"[1h])",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Partials per Hour - Pool Report",
     "type": "status-history",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "count_over_time({job=~\"fullnode\",log_mode=\"INFO\",system=\"chia\"} |=\"Submitting partial\" [1h])",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Farmer Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "targets": [
      { "expr": "api_pool_stats_farmers{}", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Pool Size TiB",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "tbytes" } },
     "targets": [
      { "expr": "api_pool_stats_poolSpaceTiB{}", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Individuel Farmer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 36 },
     "targets": [
      {
       "decimalSeparator": ".",
       "delimiter": ",",
       "schema": [
        { "name": "Date", "type": "time" },
        { "name": "LauncherID", "type": "string" },
        { "name": "points24h", "type": "number" },
        { "name": "FarmerName", "type": "string" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Wallet Balances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chia Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Chia Alt Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_confirmed_wallet_balance_coldwallet{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Flax Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Staicoin Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000"
      }
     ]
    },
    {
     "title": "Venidium Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Chia Wallet Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "chia_rpc_height{}" }
     ]
    },
    {
     "title": "Chia Alt Wallet Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "chia_rpc_height_coldwallet{}" }
     ]
    },
    {
     "title": "Flax Wallet Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "flax_rpc_height{}" }
     ]
    },
    {
     "title": "Staicoin Wallet Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "staicoin_rpc_height{}" }
     ]
    },
    {
     "title": "Venidium Wallet Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "venidium_rpc_height{}" }
     ]
    }
   ]
  },
  {
   "title": "Chia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Farmed Chia",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_farmed_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Chia Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Pool Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_confirmed_wallet_balance{wallet_id=\"2\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Chia Cold Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_confirmed_wallet_balance_coldwallet{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Chia Self Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_pool_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Chia Wallet Transaction Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_transaction_count{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Pool Wallet Transaction Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_transaction_count{wallet_id=\"2\"}"
      }
     ]
    },
    {
     "title": "Chia Cold Wallet Transaction Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_transaction_count_coldwallet{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Chia Farm Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_farmer_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Chia Max Send Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_max_send_amount{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Pool Max Send Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_max_send_amount{wallet_id=\"2\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Chia Farmed Fee",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Chia Spendable Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_spendable_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Pool Spendable Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_spendable_balance{wallet_id=\"2\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Last Height Farmed",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "chia_rpc_last_height_farmed{}" }
     ]
    },
    {
     "title": "Chia Pending Change Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_pending_change{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Pool Pending Change Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chia_rpc_pending_change{wallet_id=\"2\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flax",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_blockchain_state_height{}"
      }
     ]
    },
    {
     "title": "Fee Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_blockchain_state_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Blockchain Fee",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 4, "x": 6, "y": 6 },
     "targets": [
      {
       "expr": "flax_rpc_blockchain_state_fee_amount{}/1000000000000",
       "legendFormat": "fee amount"
      }
     ]
    },
    {
     "title": "Netspace",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 10, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_blockchain_state_netspace{}",
       "legendFormat": "netspace"
      }
     ]
    },
    {
     "title": "Farmed Flax",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_farmed_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Flax Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flax_rpc_blockchain_state_difficulty{}",
       "legendFormat": "difficulty"
      }
     ]
    },
    {
     "title": "Flax Self Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_pool_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Flax Wallet Transaction Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_transaction_count{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Flax Farm Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_farmer_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Flax Spendable Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_spendable_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Flax Farmed Fee",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Flax Pending Change Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_pending_change{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Last Height Farmed",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "flax_rpc_last_height_farmed{}" }
     ]
    },
    {
     "title": "Flax Max Send Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flax_rpc_max_send_amount{wallet_id=\"1\"}/1000000000000"
      }
     ]
    }
   ]
  },
  {
   "title": "Staicoin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_blockchain_state_height{}"
      }
     ]
    },
    {
     "title": "Fee Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_blockchain_state_fee_amount{}/1000000000"
      }
     ]
    },
    {
     "title": "Blockchain Fee",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 4, "x": 6, "y": 7 },
     "targets": [
      {
       "expr": "staicoin_rpc_blockchain_state_fee_amount{}/1000000000",
       "legendFormat": "fee amount"
      }
     ]
    },
    {
     "title": "Netspace",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 10, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_blockchain_state_netspace{}",
       "legendFormat": "netspace"
      }
     ]
    },
    {
     "title": "Farmed Staicoin",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_farmed_amount{}/1000000000"
      }
     ]
    },
    {
     "title": "Staicoin Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000"
      }
     ]
    },
    {
     "title": "Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "staicoin_rpc_blockchain_state_difficulty{}",
       "legendFormat": "difficulty"
      }
     ]
    },
    {
     "title": "Staicoin Self Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_pool_reward_amount{}/1000000000"
      }
     ]
    },
    {
     "title": "Staicoin Wallet Transaction Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_transaction_count{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Staicoin Farm Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_farmer_reward_amount{}/1000000000"
      }
     ]
    },
    {
     "title": "Staicoin Spendable Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_spendable_balance{wallet_id=\"1\"}/1000000000"
      }
     ]
    },
    {
     "title": "Staicoin Farmed Fee",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_fee_amount{}/1000000000"
      }
     ]
    },
    {
     "title": "Staicoin Pending Change Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_pending_change{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Last Height Farmed",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_last_height_farmed{}"
      }
     ]
    },
    {
     "title": "Staicoin Max Send Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "staicoin_rpc_max_send_amount{wallet_id=\"1\"}/1000000000"
      }
     ]
    }
   ]
  },
  {
   "title": "Venidium",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_blockchain_state_height{}"
      }
     ]
    },
    {
     "title": "Fee Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_blockchain_state_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Blockchain Fee",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 4, "x": 6, "y": 8 },
     "targets": [
      {
       "expr": "venidium_rpc_blockchain_state_fee_amount{}/1000000000000",
       "legendFormat": "fee amount"
      }
     ]
    },
    {
     "title": "Netspace",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_blockchain_state_netspace{}",
       "legendFormat": "netspace"
      }
     ]
    },
    {
     "title": "Farmed Venidium",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_farmed_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Venidium Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "venidium_rpc_blockchain_state_difficulty{}",
       "legendFormat": "difficulty"
      }
     ]
    },
    {
     "title": "Venidium Self Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_pool_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Venidium Wallet Transaction Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_transaction_count{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Venidium Farm Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_farmer_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Venidium Spendable Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_spendable_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Venidium Farmed Fee",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Venidium Pending Change Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_pending_change{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Last Height Farmed",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_last_height_farmed{}"
      }
     ]
    },
    {
     "title": "Venidium Max Send Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "venidium_rpc_max_send_amount{wallet_id=\"1\"}/1000000000000"
      }
     ]
    }
   ]
  },
  {
   "title": "Skynet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_blockchain_state_height{}"
      }
     ]
    },
    {
     "title": "Fee Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_blockchain_state_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Blockchain Fee",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 4, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "skynet_rpc_blockchain_state_fee_amount{}/1000000000000",
       "legendFormat": "fee amount"
      }
     ]
    },
    {
     "title": "Netspace",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_blockchain_state_netspace{}",
       "legendFormat": "netspace"
      }
     ]
    },
    {
     "title": "Farmed Skynet",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_farmed_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Skynet Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "skynet_rpc_blockchain_state_difficulty{}",
       "legendFormat": "difficulty"
      }
     ]
    },
    {
     "title": "Skynet Self Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_pool_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Skynet Wallet Transaction Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_transaction_count{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Skynet Farm Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_farmer_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Skynet Spendable Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_spendable_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Skynet Farmed Fee",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Skynet Pending Change Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_pending_change{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Last Height Farmed",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_last_height_farmed{}"
      }
     ]
    },
    {
     "title": "Skynet Max Send Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "skynet_rpc_max_send_amount{wallet_id=\"1\"}/1000000000000"
      }
     ]
    }
   ]
  },
  {
   "title": "Hddcoin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_blockchain_state_height{}"
      }
     ]
    },
    {
     "title": "Fee Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_blockchain_state_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Blockchain Fee",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 4, "x": 6, "y": 10 },
     "targets": [
      {
       "expr": "hddcoin_rpc_blockchain_state_fee_amount{}/1000000000000",
       "legendFormat": "fee amount"
      }
     ]
    },
    {
     "title": "Netspace",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 10, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_blockchain_state_netspace{}",
       "legendFormat": "netspace"
      }
     ]
    },
    {
     "title": "Farmed Hddcoin ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_farmed_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Hddcoin Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "hddcoin_rpc_blockchain_state_difficulty{}",
       "legendFormat": "difficulty"
      }
     ]
    },
    {
     "title": "Hddcoin Self Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_pool_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Hddcoin Wallet Transaction Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_transaction_count{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Hddcoin Farm Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_farmer_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Hddcoin Spendable Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_spendable_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Hddcoin Farmed Fee",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Hddcoin Pending Change Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_pending_change{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Last Height Farmed",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_last_height_farmed{}"
      }
     ]
    },
    {
     "title": "Hddcoin Max Send Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hddcoin_rpc_max_send_amount{wallet_id=\"1\"}/1000000000000"
      }
     ]
    }
   ]
  },
  {
   "title": "Aedge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_blockchain_state_height{}"
      }
     ]
    },
    {
     "title": "Fee Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_blockchain_state_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Blockchain Fee",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 4, "x": 6, "y": 11 },
     "targets": [
      {
       "expr": "aedge_rpc_blockchain_state_fee_amount{}/1000000000000",
       "legendFormat": "fee amount"
      }
     ]
    },
    {
     "title": "Netspace",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_blockchain_state_netspace{}",
       "legendFormat": "netspace"
      }
     ]
    },
    {
     "title": "Farmed Aedge",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_farmed_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Aedge Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aedge_rpc_blockchain_state_difficulty{}",
       "legendFormat": "difficulty"
      }
     ]
    },
    {
     "title": "Aedge Self Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_pool_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Aedge Wallet Transaction Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_transaction_count{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Aedge Farm Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_farmer_reward_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Aedge Spendable Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_spendable_balance{wallet_id=\"1\"}/1000000000000"
      }
     ]
    },
    {
     "title": "Aedge Farmed Fee",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Aedge Pending Change Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_pending_change{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Last Height Farmed",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "aedge_rpc_last_height_farmed{}" }
     ]
    },
    {
     "title": "Aedge Max Send Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aedge_rpc_max_send_amount{wallet_id=\"1\"}/1000000000000"
      }
     ]
    }
   ]
  },
  {
   "title": "Ethgreen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Height",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_blockchain_state_height{}"
      }
     ]
    },
    {
     "title": "Fee Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_blockchain_state_fee_amount{}/1000000000000"
      }
     ]
    },
    {
     "title": "Blockchain Fee",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 4, "x": 6, "y": 12 },
     "targets": [
      {
       "expr": "ethgreen_rpc_blockchain_state_fee_amount{}/1000000000000",
       "legendFormat": "fee amount"
      }
     ]
    },
    {
     "title": "Netspace",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_blockchain_state_netspace{}",
       "legendFormat": "netspace"
      }
     ]
    },
    {
     "title": "Farmed Ethgreen",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_farmed_amount{}/10000000000"
      }
     ]
    },
    {
     "title": "Ethgreen Wallet Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_confirmed_wallet_balance{wallet_id=\"1\"}/10000000000"
      }
     ]
    },
    {
     "title": "Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ethgreen_rpc_blockchain_state_difficulty{}",
       "legendFormat": "difficulty"
      }
     ]
    },
    {
     "title": "Ethgreen Self Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_pool_reward_amount{}/10000000000"
      }
     ]
    },
    {
     "title": "Ethgreen Wallet Transaction Count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_transaction_count{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Ethgreen Farm Reward",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_farmer_reward_amount{}/10000000000"
      }
     ]
    },
    {
     "title": "Ethgreen Spendable Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_spendable_balance{wallet_id=\"1\"}/10000000000"
      }
     ]
    },
    {
     "title": "Ethgreen Farmed Fee",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_fee_amount{}/10000000000"
      }
     ]
    },
    {
     "title": "Ethgreen Pending Change Balance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_pending_change{wallet_id=\"1\"}"
      }
     ]
    },
    {
     "title": "Last Height Farmed",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_last_height_farmed{}"
      }
     ]
    },
    {
     "title": "Ethgreen Max Send Amount",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ethgreen_rpc_max_send_amount{wallet_id=\"1\"}/10000000000"
      }
     ]
    }
   ]
  }
 ]
}